import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { Input, Button, ButtonGroup, FormControl } from "@chakra-ui/react";
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useContractEvent, useSigner, useAccount, useBalance, useContract } from 'wagmi'
import artifact from '@/pages/Bank.json'

const inter = Inter({ subsets: ["latin"] });

const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3"

const Logo = () => (<div>the logo</div>)

export default function Home() {
  const [deposit, setDeposit] = useState(0);
  const [withdrawAmount, setWithdrawAmount] = useState(0);
  const { address } = useAccount()
  const { data, isError, isLoading } = useBalance({address: contractAddress})
  const { data: signer, isSignerError, isSignerLoading } = useSigner()
  const contract = useContract({address: contractAddress, abi: artifact.abi, signerOrProvider: signer})


 //Get All the Events
  //       let filter = {
  //           address: contractAddress,
  //           fromBlock: 0
  //       };

  //       let events = await contract.queryFilter(filter)

  // getTransactionReceipt
  // for await (const event of events) { }

  useContractEvent({
    address: contractAddress,
    abi: artifact.abi,
    eventName: 'etherDeposited',
    listener(node, resolver) {
      console.log('deposit', node, resolver)
    },
  })

  useContractEvent({
    address: contractAddress,
    abi: artifact.abi,
    eventName: 'etherWithdrawed',
    listener(node, resolver) {
      console.log('withdrawed', node, resolver)
    },
  })


  // contract.on("etherDeposited", (account, amount) => {}
  const Balance = () => {
    console.log({data})
    return (
      <div>Balance: {data?.formatted} {data?.symbol}</div>
    )
  }

  const sendDeposit = async () => {
    console.log("you deposit", deposit)
    await contract.deposit({value: deposit})
    setDeposit(0)
  }

  const withdraw = async () => {
    await contract.withdraw(withdrawAmount)
    setWithdrawAmount(0)
  }
  return (
    <>
      <Head>
        <title>Increment decrement app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo/>
      <ConnectButton />
      <div>Bank DAPP</div>
    { (isLoading && <div>loading...</div>) || <Balance /> }
      <h2>Deposit</h2>
      <FormControl >
        <Input placeholder='Amount' onChange={(e) => setDeposit(e.target.value)}/>
        <Button onClick={sendDeposit}>Deposit</Button>
      </FormControl>
      <h2>Withdraw</h2>
      <FormControl >
        <Input placeholder='Amount' onChange={(e) => setWithdrawAmount(e.target.value)}/>
        <Button onClick={withdraw}>Withdraw</Button>
      </FormControl>

      <h2>Last events</h2>
    </>
  );
}
